/* Generated By:JJTree: Do not edit this line. ASTArraySpecifier.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cleanroommc.kirino.gl.shader.parser;

public
class ASTArraySpecifier extends SimpleNode {
  public ASTArraySpecifier(int id) {
    super(id);
  }

  public ASTArraySpecifier(GLSLResourceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Void jjtAccept(GLSLResourceParserVisitor visitor, Void data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0688724842bab08e81acdc20246328b3 (do not edit this line) */
