/* Generated By:JJTree: Do not edit this line. ASTDeclaratorList.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cleanroommc.kirino.gl.shader.parser;

public
class ASTDeclaratorList extends SimpleNode {
  public ASTDeclaratorList(int id) {
    super(id);
  }

  public ASTDeclaratorList(GLSLResourceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Void jjtAccept(GLSLResourceParserVisitor visitor, Void data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e1b11bb3e0e9186ee3318e5ea3ed4cc7 (do not edit this line) */
