/* Generated By:JJTree: Do not edit this line. ASTGlobalLayoutDeclaration.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cleanroommc.kirino.gl.shader.parser;

public
class ASTGlobalLayoutDeclaration extends SimpleNode {
  public ASTGlobalLayoutDeclaration(int id) {
    super(id);
  }

  public ASTGlobalLayoutDeclaration(GLSLResourceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Void jjtAccept(GLSLResourceParserVisitor visitor, Void data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=551c01b5b139c43a292f402f82a24ef5 (do not edit this line) */
