/* Generated By:JJTree: Do not edit this line. ASTInstanceDeclarator.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cleanroommc.kirino.gl.shader.parser;

public
class ASTInstanceDeclarator extends SimpleNode {
  public ASTInstanceDeclarator(int id) {
    super(id);
  }

  public ASTInstanceDeclarator(GLSLResourceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Void jjtAccept(GLSLResourceParserVisitor visitor, Void data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a0585a1da5ec75f7b89419f99a5e0c18 (do not edit this line) */
