/* Generated By:JJTree: Do not edit this line. ASTInterfaceBlockDeclaration.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cleanroommc.kirino.gl.shader.parser;

public
class ASTInterfaceBlockDeclaration extends SimpleNode {
  public ASTInterfaceBlockDeclaration(int id) {
    super(id);
  }

  public ASTInterfaceBlockDeclaration(GLSLResourceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Void jjtAccept(GLSLResourceParserVisitor visitor, Void data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b77607d295057857292a9a7d81e77aad (do not edit this line) */
