/* Generated By:JJTree: Do not edit this line. ASTInitializer.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cleanroommc.kirino.gl.shader.parser;

public
class ASTInitializer extends SimpleNode {
  public ASTInitializer(int id) {
    super(id);
  }

  public ASTInitializer(GLSLResourceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Void jjtAccept(GLSLResourceParserVisitor visitor, Void data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4f3d7ad871ff908be91346d9d83b1d3e (do not edit this line) */
