/* Generated By:JJTree: Do not edit this line. ASTLayoutQualifierItem.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cleanroommc.kirino.gl.shader.parser;

public
class ASTLayoutQualifierItem extends SimpleNode {
  public ASTLayoutQualifierItem(int id) {
    super(id);
  }

  public ASTLayoutQualifierItem(GLSLResourceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Void jjtAccept(GLSLResourceParserVisitor visitor, Void data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=71f4eda49109f402c982477ee8460128 (do not edit this line) */
