/* Generated By:JJTree: Do not edit this line. ASTLayoutQualifier.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cleanroommc.kirino.gl.shader.parser;

public
class ASTLayoutQualifier extends SimpleNode {
  public ASTLayoutQualifier(int id) {
    super(id);
  }

  public ASTLayoutQualifier(GLSLResourceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Void jjtAccept(GLSLResourceParserVisitor visitor, Void data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9afff8ebbb63dd5d3d580ac528dd68e8 (do not edit this line) */
