/* Generated By:JJTree: Do not edit this line. ASTStructSpecifier.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cleanroommc.kirino.gl.shader.parser;

public
class ASTStructSpecifier extends SimpleNode {
  public ASTStructSpecifier(int id) {
    super(id);
  }

  public ASTStructSpecifier(GLSLResourceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Void jjtAccept(GLSLResourceParserVisitor visitor, Void data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cff43f66ad028fb09e586a650a0b8e7e (do not edit this line) */
