/* Generated By:JJTree: Do not edit this line. ASTTranslationUnit.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cleanroommc.kirino.gl.shader.parser;

public
class ASTTranslationUnit extends SimpleNode {
  public ASTTranslationUnit(int id) {
    super(id);
  }

  public ASTTranslationUnit(GLSLResourceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Void jjtAccept(GLSLResourceParserVisitor visitor, Void data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=63c7991b4d8ce90deac46d07ee78b711 (do not edit this line) */
