/* Generated By:JJTree: Do not edit this line. ASTTypeSpecifier.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cleanroommc.kirino.gl.shader.parser;

public
class ASTTypeSpecifier extends SimpleNode {
  public ASTTypeSpecifier(int id) {
    super(id);
  }

  public ASTTypeSpecifier(GLSLResourceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Void jjtAccept(GLSLResourceParserVisitor visitor, Void data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=516f251c3e943cf67cfcefbd94f13dac (do not edit this line) */
