/* GLSLResourceParser.java */
/* Generated By:JJTree&JavaCC: Do not edit this line. GLSLResourceParser.java */
package com.cleanroommc.kirino.gl.shader.parser;

public class GLSLResourceParser/*@bgen(jjtree)*/implements GLSLResourceParserTreeConstants, GLSLResourceParserConstants {/*@bgen(jjtree)*/
  protected JJTGLSLResourceParserState jjtree = new JJTGLSLResourceParserState();
    public record LayoutQualifierValue(String name, String expression) {
    }

    private record ResourcePrefix(int storageKind, int firstTokenAfterQualifiers) {
    }

    private boolean isInterfaceBlockAhead() {
        ResourcePrefix prefix = scanResourcePrefix();
        if (prefix == null) {
            return false;
        }

        int i = prefix.firstTokenAfterQualifiers;
        return getToken(i).kind == IDENTIFIER && getToken(i + 1).kind == LEFT_BRACE;
    }

    private boolean isUniformDeclarationAhead() {
        ResourcePrefix prefix = scanResourcePrefix();
        if (prefix == null || prefix.storageKind != UNIFORM) {
            return false;
        }

        int i = prefix.firstTokenAfterQualifiers;
        if (getToken(i).kind == IDENTIFIER && getToken(i + 1).kind == LEFT_BRACE) {
            return false;
        }

        return getToken(i).kind == IDENTIFIER || getToken(i).kind == STRUCT;
    }

    private boolean isStructDeclarationAhead() {
        int i = 1;
        if (getToken(i).kind != STRUCT) {
            return false;
        }

        i++;
        if (getToken(i).kind == IDENTIFIER) {
            i++;
        }
        return getToken(i).kind == LEFT_BRACE;
    }

    private ResourcePrefix scanResourcePrefix() {
        int i = 1;
        int storageKind = -1;
        boolean consumedQualifier = false;

        while (true) {
            int kind = getToken(i).kind;
            if (kind == LAYOUT) {
                i = tokenAfterLayoutQualifier(i);
                if (i < 0) {
                    return null;
                }
                consumedQualifier = true;
                continue;
            }

            if (!isSimpleQualifierKind(kind)) {
                break;
            }

            if (kind == UNIFORM || kind == BUFFER) {
                if (storageKind != -1) {
                    return null;
                }
                storageKind = kind;
            }
            consumedQualifier = true;
            i++;
        }

        if (!consumedQualifier || storageKind == -1) {
            return null;
        }
        return new ResourcePrefix(storageKind, i);
    }

    private int tokenAfterLayoutQualifier(int layoutIndex) {
        int i = layoutIndex + 1;
        if (getToken(i).kind != LEFT_PAREN) {
            return -1;
        }

        int depth = 1;
        i++;
        while (depth > 0) {
            int kind = getToken(i).kind;
            if (kind == EOF) {
                return -1;
            }
            if (kind == LEFT_PAREN) {
                depth++;
            } else if (kind == RIGHT_PAREN) {
                depth--;
            }
            i++;
        }
        return i;
    }

    private static boolean isSimpleQualifierKind(int kind) {
        switch (kind) {
            case CONST:
            case IN:
            case OUT:
            case INOUT:
            case CENTROID:
            case PATCH:
            case SAMPLE:
            case UNIFORM:
            case BUFFER:
            case SHARED:
            case COHERENT:
            case VOLATILE:
            case RESTRICT:
            case READONLY:
            case WRITEONLY:
            case ATTRIBUTE:
            case VARYING:
            case SMOOTH:
            case FLAT:
            case NOPERSPECTIVE:
            case INVARIANT:
            case PRECISE:
            case HIGHP:
            case MEDIUMP:
            case LOWP:
                return true;
            default:
                return false;
        }
    }

    private String consumeExpressionUntil(int firstStopKind, int secondStopKind) throws ParseException {
        StringBuilder result = new StringBuilder();
        int parenDepth = 0;
        int bracketDepth = 0;
        int braceDepth = 0;

        while (true) {
            Token next = getToken(1);
            int kind = next.kind;

            if (kind == EOF) {
                throw new ParseException("Unexpected end of input inside expression.");
            }
            if (parenDepth == 0 && bracketDepth == 0 && braceDepth == 0
                    && (kind == firstStopKind || kind == secondStopKind)) {
                break;
            }

            Token consumed = getNextToken();
            appendNormalizedToken(result, consumed.image);

            if (kind == LEFT_PAREN) {
                parenDepth++;
            } else if (kind == RIGHT_PAREN) {
                if (parenDepth == 0) {
                    throw new ParseException("Unbalanced ')' inside expression.");
                }
                parenDepth--;
            } else if (kind == LEFT_BRACKET) {
                bracketDepth++;
            } else if (kind == RIGHT_BRACKET) {
                if (bracketDepth == 0) {
                    throw new ParseException("Unbalanced ']' inside expression.");
                }
                bracketDepth--;
            } else if (kind == LEFT_BRACE) {
                braceDepth++;
            } else if (kind == RIGHT_BRACE) {
                if (braceDepth == 0) {
                    throw new ParseException("Unbalanced '}' inside expression.");
                }
                braceDepth--;
            }
        }

        if (result.isEmpty()) {
            throw new ParseException("Expected an expression.");
        }
        return result.toString();
    }

    private static void appendNormalizedToken(StringBuilder result, String image) {
        if (!result.isEmpty()
                && isWordCharacter(result.charAt(result.length() - 1))
                && !image.isEmpty()
                && isWordCharacter(image.charAt(0))) {
            result.append(' ');
        }
        result.append(image);
    }

    private static boolean isWordCharacter(char c) {
        return Character.isLetterOrDigit(c) || c == '_';
    }

    private void skipExternalDeclaration(int firstKind) {
        int parenDepth = 0;
        int bracketDepth = 0;
        int braceDepth = 0;
        boolean sawTopLevelBrace = false;
        int kind = firstKind;

        while (true) {
            if (kind == LEFT_PAREN) {
                parenDepth++;
            } else if (kind == RIGHT_PAREN) {
                if (parenDepth > 0) {
                    parenDepth--;
                }
            } else if (kind == LEFT_BRACKET) {
                bracketDepth++;
            } else if (kind == RIGHT_BRACKET) {
                if (bracketDepth > 0) {
                    bracketDepth--;
                }
            } else if (kind == LEFT_BRACE) {
                if (parenDepth == 0 && bracketDepth == 0 && braceDepth == 0) {
                    sawTopLevelBrace = true;
                }
                braceDepth++;
            } else if (kind == RIGHT_BRACE) {
                if (braceDepth > 0) {
                    braceDepth--;
                }
                if (sawTopLevelBrace && parenDepth == 0 && bracketDepth == 0 && braceDepth == 0) {
                    if (getToken(1).kind == SEMICOLON) {
                        getNextToken();
                    }
                    return;
                }
            } else if (kind == SEMICOLON && parenDepth == 0 && bracketDepth == 0 && braceDepth == 0) {
                return;
            }

            kind = getToken(1).kind;
            if (kind == EOF) {
                return;
            }
            getNextToken();
        }
    }

  final public ASTTranslationUnit TranslationUnit() throws ParseException {/*@bgen(jjtree) TranslationUnit */
  ASTTranslationUnit jjtn000 = new ASTTranslationUnit(JJTTRANSLATIONUNIT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      label_1:
      while (true) {
        if (jj_2_1(1)) {
          ;
        } else {
          break label_1;
        }
        if (isInterfaceBlockAhead()) {
          InterfaceBlockDeclaration();
        } else if (isUniformDeclarationAhead()) {
          UniformDeclaration();
        } else if (isStructDeclarationAhead()) {
          StructDeclaration();
        } else {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case LAYOUT:
          case STRUCT:
          case UNIFORM:
          case BUFFER:
          case CONST:
          case INOUT:
          case IN:
          case OUT:
          case CENTROID:
          case PATCH:
          case SAMPLE:
          case SHARED:
          case COHERENT:
          case VOLATILE:
          case RESTRICT:
          case READONLY:
          case WRITEONLY:
          case ATTRIBUTE:
          case VARYING:
          case SMOOTH:
          case FLAT:
          case NOPERSPECTIVE:
          case INVARIANT:
          case PRECISE:
          case HIGHP:
          case MEDIUMP:
          case LOWP:
          case TRUE:
          case FALSE:
          case NUMBER:
          case IDENTIFIER:
          case LEFT_PAREN:
          case RIGHT_PAREN:
          case LEFT_BRACKET:
          case RIGHT_BRACKET:
          case LEFT_BRACE:
          case RIGHT_BRACE:
          case COMMA:
          case SEMICOLON:
          case EQUAL:
          case OTHER:{
            SkipExternalDeclaration();
            break;
            }
          default:
            jj_la1[0] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      }
      jj_consume_token(0);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
      jjtn000.jjtSetLastToken(getToken(0));
{if ("" != null) return jjtn000;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
        jjtn000.jjtSetLastToken(getToken(0));
      }
    }
    throw new Error("Missing return statement in function");
}

  final public void InterfaceBlockDeclaration() throws ParseException {/*@bgen(jjtree) InterfaceBlockDeclaration */
  ASTInterfaceBlockDeclaration jjtn000 = new ASTInterfaceBlockDeclaration(JJTINTERFACEBLOCKDECLARATION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      label_2:
      while (true) {
        Qualifier();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LAYOUT:
        case UNIFORM:
        case BUFFER:
        case CONST:
        case INOUT:
        case IN:
        case OUT:
        case CENTROID:
        case PATCH:
        case SAMPLE:
        case SHARED:
        case COHERENT:
        case VOLATILE:
        case RESTRICT:
        case READONLY:
        case WRITEONLY:
        case ATTRIBUTE:
        case VARYING:
        case SMOOTH:
        case FLAT:
        case NOPERSPECTIVE:
        case INVARIANT:
        case PRECISE:
        case HIGHP:
        case MEDIUMP:
        case LOWP:{
          ;
          break;
          }
        default:
          jj_la1[1] = jj_gen;
          break label_2;
        }
      }
      BlockName();
      jj_consume_token(LEFT_BRACE);
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LAYOUT:
        case STRUCT:
        case UNIFORM:
        case BUFFER:
        case CONST:
        case INOUT:
        case IN:
        case OUT:
        case CENTROID:
        case PATCH:
        case SAMPLE:
        case SHARED:
        case COHERENT:
        case VOLATILE:
        case RESTRICT:
        case READONLY:
        case WRITEONLY:
        case ATTRIBUTE:
        case VARYING:
        case SMOOTH:
        case FLAT:
        case NOPERSPECTIVE:
        case INVARIANT:
        case PRECISE:
        case HIGHP:
        case MEDIUMP:
        case LOWP:
        case IDENTIFIER:{
          ;
          break;
          }
        default:
          jj_la1[2] = jj_gen;
          break label_3;
        }
        MemberDeclaration();
      }
      jj_consume_token(RIGHT_BRACE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        InstanceDeclarator();
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        ;
      }
      jj_consume_token(SEMICOLON);
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
        jjtn000.jjtSetLastToken(getToken(0));
      }
    }
}

  final public void UniformDeclaration() throws ParseException {/*@bgen(jjtree) UniformDeclaration */
  ASTUniformDeclaration jjtn000 = new ASTUniformDeclaration(JJTUNIFORMDECLARATION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      label_4:
      while (true) {
        Qualifier();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LAYOUT:
        case UNIFORM:
        case BUFFER:
        case CONST:
        case INOUT:
        case IN:
        case OUT:
        case CENTROID:
        case PATCH:
        case SAMPLE:
        case SHARED:
        case COHERENT:
        case VOLATILE:
        case RESTRICT:
        case READONLY:
        case WRITEONLY:
        case ATTRIBUTE:
        case VARYING:
        case SMOOTH:
        case FLAT:
        case NOPERSPECTIVE:
        case INVARIANT:
        case PRECISE:
        case HIGHP:
        case MEDIUMP:
        case LOWP:{
          ;
          break;
          }
        default:
          jj_la1[4] = jj_gen;
          break label_4;
        }
      }
      TypeSpecifier();
      DeclaratorList();
      jj_consume_token(SEMICOLON);
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
        jjtn000.jjtSetLastToken(getToken(0));
      }
    }
}

  final public void StructDeclaration() throws ParseException {/*@bgen(jjtree) StructDeclaration */
  ASTStructDeclaration jjtn000 = new ASTStructDeclaration(JJTSTRUCTDECLARATION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      StructSpecifier();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        DeclaratorList();
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        ;
      }
      jj_consume_token(SEMICOLON);
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
        jjtn000.jjtSetLastToken(getToken(0));
      }
    }
}

  final public void StructSpecifier() throws ParseException {/*@bgen(jjtree) StructSpecifier */
  ASTStructSpecifier jjtn000 = new ASTStructSpecifier(JJTSTRUCTSPECIFIER);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      jj_consume_token(STRUCT);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        StructName();
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        ;
      }
      jj_consume_token(LEFT_BRACE);
      label_5:
      while (true) {
        MemberDeclaration();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LAYOUT:
        case STRUCT:
        case UNIFORM:
        case BUFFER:
        case CONST:
        case INOUT:
        case IN:
        case OUT:
        case CENTROID:
        case PATCH:
        case SAMPLE:
        case SHARED:
        case COHERENT:
        case VOLATILE:
        case RESTRICT:
        case READONLY:
        case WRITEONLY:
        case ATTRIBUTE:
        case VARYING:
        case SMOOTH:
        case FLAT:
        case NOPERSPECTIVE:
        case INVARIANT:
        case PRECISE:
        case HIGHP:
        case MEDIUMP:
        case LOWP:
        case IDENTIFIER:{
          ;
          break;
          }
        default:
          jj_la1[7] = jj_gen;
          break label_5;
        }
      }
      jj_consume_token(RIGHT_BRACE);
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
        jjtn000.jjtSetLastToken(getToken(0));
      }
    }
}

  final public void MemberDeclaration() throws ParseException {/*@bgen(jjtree) MemberDeclaration */
  ASTMemberDeclaration jjtn000 = new ASTMemberDeclaration(JJTMEMBERDECLARATION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LAYOUT:
        case UNIFORM:
        case BUFFER:
        case CONST:
        case INOUT:
        case IN:
        case OUT:
        case CENTROID:
        case PATCH:
        case SAMPLE:
        case SHARED:
        case COHERENT:
        case VOLATILE:
        case RESTRICT:
        case READONLY:
        case WRITEONLY:
        case ATTRIBUTE:
        case VARYING:
        case SMOOTH:
        case FLAT:
        case NOPERSPECTIVE:
        case INVARIANT:
        case PRECISE:
        case HIGHP:
        case MEDIUMP:
        case LOWP:{
          ;
          break;
          }
        default:
          jj_la1[8] = jj_gen;
          break label_6;
        }
        Qualifier();
      }
      TypeSpecifier();
      MemberDeclaratorList();
      jj_consume_token(SEMICOLON);
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
        jjtn000.jjtSetLastToken(getToken(0));
      }
    }
}

  final public void TypeSpecifier() throws ParseException {/*@bgen(jjtree) TypeSpecifier */
  ASTTypeSpecifier jjtn000 = new ASTTypeSpecifier(JJTTYPESPECIFIER);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));Token type = null;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        type = jj_consume_token(IDENTIFIER);
jjtn000.jjtSetValue(type.image);
        break;
        }
      case STRUCT:{
        StructSpecifier();
jjtn000.jjtSetValue("struct");
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LEFT_BRACKET:{
        ArraySpecifier();
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        ;
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
        jjtn000.jjtSetLastToken(getToken(0));
      }
    }
}

  final public void Qualifier() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LAYOUT:{
      LayoutQualifier();
      break;
      }
    case UNIFORM:
    case BUFFER:{
      StorageQualifier();
      break;
      }
    case CONST:
    case INOUT:
    case IN:
    case OUT:
    case CENTROID:
    case PATCH:
    case SAMPLE:
    case SHARED:
    case COHERENT:
    case VOLATILE:
    case RESTRICT:
    case READONLY:
    case WRITEONLY:
    case ATTRIBUTE:
    case VARYING:
    case SMOOTH:
    case FLAT:
    case NOPERSPECTIVE:
    case INVARIANT:
    case PRECISE:
    case HIGHP:
    case MEDIUMP:
    case LOWP:{
      SimpleQualifier();
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void LayoutQualifier() throws ParseException {/*@bgen(jjtree) LayoutQualifier */
  ASTLayoutQualifier jjtn000 = new ASTLayoutQualifier(JJTLAYOUTQUALIFIER);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      jj_consume_token(LAYOUT);
      jj_consume_token(LEFT_PAREN);
      LayoutQualifierItem();
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[12] = jj_gen;
          break label_7;
        }
        jj_consume_token(COMMA);
        LayoutQualifierItem();
      }
      jj_consume_token(RIGHT_PAREN);
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
        jjtn000.jjtSetLastToken(getToken(0));
      }
    }
}

  final public void LayoutQualifierItem() throws ParseException {/*@bgen(jjtree) LayoutQualifierItem */
  ASTLayoutQualifierItem jjtn000 = new ASTLayoutQualifierItem(JJTLAYOUTQUALIFIERITEM);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));Token name; String expression = null;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        name = jj_consume_token(IDENTIFIER);
        break;
        }
      case SHARED:{
        name = jj_consume_token(SHARED);
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQUAL:{
        jj_consume_token(EQUAL);
expression = consumeExpressionUntil(COMMA, RIGHT_PAREN);
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        ;
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
      jjtn000.jjtSetLastToken(getToken(0));
jjtn000.jjtSetValue(new LayoutQualifierValue(name.image, expression));
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
        jjtn000.jjtSetLastToken(getToken(0));
      }
    }
}

  final public void StorageQualifier() throws ParseException {/*@bgen(jjtree) StorageQualifier */
  ASTStorageQualifier jjtn000 = new ASTStorageQualifier(JJTSTORAGEQUALIFIER);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));Token qualifier;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case UNIFORM:{
        qualifier = jj_consume_token(UNIFORM);
        break;
        }
      case BUFFER:{
        qualifier = jj_consume_token(BUFFER);
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
      jjtn000.jjtSetLastToken(getToken(0));
jjtn000.jjtSetValue(qualifier.image);
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
        jjtn000.jjtSetLastToken(getToken(0));
      }
    }
}

  final public void SimpleQualifier() throws ParseException {/*@bgen(jjtree) Qualifier */
  ASTQualifier jjtn000 = new ASTQualifier(JJTQUALIFIER);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));Token qualifier;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CONST:{
        qualifier = jj_consume_token(CONST);
        break;
        }
      case IN:{
        qualifier = jj_consume_token(IN);
        break;
        }
      case OUT:{
        qualifier = jj_consume_token(OUT);
        break;
        }
      case INOUT:{
        qualifier = jj_consume_token(INOUT);
        break;
        }
      case CENTROID:{
        qualifier = jj_consume_token(CENTROID);
        break;
        }
      case PATCH:{
        qualifier = jj_consume_token(PATCH);
        break;
        }
      case SAMPLE:{
        qualifier = jj_consume_token(SAMPLE);
        break;
        }
      case SHARED:{
        qualifier = jj_consume_token(SHARED);
        break;
        }
      case COHERENT:{
        qualifier = jj_consume_token(COHERENT);
        break;
        }
      case VOLATILE:{
        qualifier = jj_consume_token(VOLATILE);
        break;
        }
      case RESTRICT:{
        qualifier = jj_consume_token(RESTRICT);
        break;
        }
      case READONLY:{
        qualifier = jj_consume_token(READONLY);
        break;
        }
      case WRITEONLY:{
        qualifier = jj_consume_token(WRITEONLY);
        break;
        }
      case ATTRIBUTE:{
        qualifier = jj_consume_token(ATTRIBUTE);
        break;
        }
      case VARYING:{
        qualifier = jj_consume_token(VARYING);
        break;
        }
      case SMOOTH:{
        qualifier = jj_consume_token(SMOOTH);
        break;
        }
      case FLAT:{
        qualifier = jj_consume_token(FLAT);
        break;
        }
      case NOPERSPECTIVE:{
        qualifier = jj_consume_token(NOPERSPECTIVE);
        break;
        }
      case INVARIANT:{
        qualifier = jj_consume_token(INVARIANT);
        break;
        }
      case PRECISE:{
        qualifier = jj_consume_token(PRECISE);
        break;
        }
      case HIGHP:{
        qualifier = jj_consume_token(HIGHP);
        break;
        }
      case MEDIUMP:{
        qualifier = jj_consume_token(MEDIUMP);
        break;
        }
      case LOWP:{
        qualifier = jj_consume_token(LOWP);
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
      jjtn000.jjtSetLastToken(getToken(0));
jjtn000.jjtSetValue(qualifier.image);
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
        jjtn000.jjtSetLastToken(getToken(0));
      }
    }
}

  final public void DeclaratorList() throws ParseException {/*@bgen(jjtree) DeclaratorList */
  ASTDeclaratorList jjtn000 = new ASTDeclaratorList(JJTDECLARATORLIST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      Declarator();
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[17] = jj_gen;
          break label_8;
        }
        jj_consume_token(COMMA);
        Declarator();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
        jjtn000.jjtSetLastToken(getToken(0));
      }
    }
}

  final public void Declarator() throws ParseException {/*@bgen(jjtree) Declarator */
  ASTDeclarator jjtn000 = new ASTDeclarator(JJTDECLARATOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));Token name;
    try {
      name = jj_consume_token(IDENTIFIER);
jjtn000.jjtSetValue(name.image);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LEFT_BRACKET:{
        ArraySpecifier();
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQUAL:{
        Initializer();
        break;
        }
      default:
        jj_la1[19] = jj_gen;
        ;
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
        jjtn000.jjtSetLastToken(getToken(0));
      }
    }
}

  final public void MemberDeclaratorList() throws ParseException {/*@bgen(jjtree) DeclaratorList */
  ASTDeclaratorList jjtn000 = new ASTDeclaratorList(JJTDECLARATORLIST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      MemberDeclarator();
      label_9:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[20] = jj_gen;
          break label_9;
        }
        jj_consume_token(COMMA);
        MemberDeclarator();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
        jjtn000.jjtSetLastToken(getToken(0));
      }
    }
}

  final public void MemberDeclarator() throws ParseException {/*@bgen(jjtree) Declarator */
  ASTDeclarator jjtn000 = new ASTDeclarator(JJTDECLARATOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));Token name;
    try {
      name = jj_consume_token(IDENTIFIER);
jjtn000.jjtSetValue(name.image);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LEFT_BRACKET:{
        ArraySpecifier();
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        ;
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
        jjtn000.jjtSetLastToken(getToken(0));
      }
    }
}

  final public void InstanceDeclarator() throws ParseException {/*@bgen(jjtree) InstanceDeclarator */
  ASTInstanceDeclarator jjtn000 = new ASTInstanceDeclarator(JJTINSTANCEDECLARATOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));Token name;
    try {
      name = jj_consume_token(IDENTIFIER);
jjtn000.jjtSetValue(name.image);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LEFT_BRACKET:{
        ArraySpecifier();
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        ;
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
        jjtn000.jjtSetLastToken(getToken(0));
      }
    }
}

  final public void ArraySpecifier() throws ParseException {/*@bgen(jjtree) ArraySpecifier */
  ASTArraySpecifier jjtn000 = new ASTArraySpecifier(JJTARRAYSPECIFIER);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));
    try {
      label_10:
      while (true) {
        ArrayDimension();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LEFT_BRACKET:{
          ;
          break;
          }
        default:
          jj_la1[23] = jj_gen;
          break label_10;
        }
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
        jjtn000.jjtSetLastToken(getToken(0));
      }
    }
}

  final public void ArrayDimension() throws ParseException {/*@bgen(jjtree) ArrayDimension */
  ASTArrayDimension jjtn000 = new ASTArrayDimension(JJTARRAYDIMENSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));String expression = null;
    try {
      jj_consume_token(LEFT_BRACKET);
if (getToken(1).kind != RIGHT_BRACKET) {
            expression = consumeExpressionUntil(RIGHT_BRACKET, -1);
        }
      jj_consume_token(RIGHT_BRACKET);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
      jjtn000.jjtSetLastToken(getToken(0));
jjtn000.jjtSetValue(expression);
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
        jjtn000.jjtSetLastToken(getToken(0));
      }
    }
}

  final public void Initializer() throws ParseException {/*@bgen(jjtree) Initializer */
  ASTInitializer jjtn000 = new ASTInitializer(JJTINITIALIZER);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));String expression;
    try {
      jj_consume_token(EQUAL);
expression = consumeExpressionUntil(COMMA, SEMICOLON);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
      jjtn000.jjtSetLastToken(getToken(0));
jjtn000.jjtSetValue(expression);
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
        jjtn000.jjtSetLastToken(getToken(0));
      }
    }
}

  final public void BlockName() throws ParseException {/*@bgen(jjtree) BlockName */
  ASTBlockName jjtn000 = new ASTBlockName(JJTBLOCKNAME);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));Token name;
    try {
      name = jj_consume_token(IDENTIFIER);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
      jjtn000.jjtSetLastToken(getToken(0));
jjtn000.jjtSetValue(name.image);
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
        jjtn000.jjtSetLastToken(getToken(0));
      }
    }
}

  final public void StructName() throws ParseException {/*@bgen(jjtree) StructName */
  ASTStructName jjtn000 = new ASTStructName(JJTSTRUCTNAME);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
  jjtn000.jjtSetFirstToken(getToken(1));Token name;
    try {
      name = jj_consume_token(IDENTIFIER);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
      jjtn000.jjtSetLastToken(getToken(0));
jjtn000.jjtSetValue(name.image);
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
        jjtn000.jjtSetLastToken(getToken(0));
      }
    }
}

  final public void SkipExternalDeclaration() throws ParseException {Token first;
    first = AnyToken();
skipExternalDeclaration(first.kind);
}

  final public Token AnyToken() throws ParseException {Token token;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LAYOUT:{
      token = jj_consume_token(LAYOUT);
      break;
      }
    case STRUCT:{
      token = jj_consume_token(STRUCT);
      break;
      }
    case UNIFORM:{
      token = jj_consume_token(UNIFORM);
      break;
      }
    case BUFFER:{
      token = jj_consume_token(BUFFER);
      break;
      }
    case CONST:{
      token = jj_consume_token(CONST);
      break;
      }
    case INOUT:{
      token = jj_consume_token(INOUT);
      break;
      }
    case IN:{
      token = jj_consume_token(IN);
      break;
      }
    case OUT:{
      token = jj_consume_token(OUT);
      break;
      }
    case CENTROID:{
      token = jj_consume_token(CENTROID);
      break;
      }
    case PATCH:{
      token = jj_consume_token(PATCH);
      break;
      }
    case SAMPLE:{
      token = jj_consume_token(SAMPLE);
      break;
      }
    case SHARED:{
      token = jj_consume_token(SHARED);
      break;
      }
    case COHERENT:{
      token = jj_consume_token(COHERENT);
      break;
      }
    case VOLATILE:{
      token = jj_consume_token(VOLATILE);
      break;
      }
    case RESTRICT:{
      token = jj_consume_token(RESTRICT);
      break;
      }
    case READONLY:{
      token = jj_consume_token(READONLY);
      break;
      }
    case WRITEONLY:{
      token = jj_consume_token(WRITEONLY);
      break;
      }
    case ATTRIBUTE:{
      token = jj_consume_token(ATTRIBUTE);
      break;
      }
    case VARYING:{
      token = jj_consume_token(VARYING);
      break;
      }
    case SMOOTH:{
      token = jj_consume_token(SMOOTH);
      break;
      }
    case FLAT:{
      token = jj_consume_token(FLAT);
      break;
      }
    case NOPERSPECTIVE:{
      token = jj_consume_token(NOPERSPECTIVE);
      break;
      }
    case INVARIANT:{
      token = jj_consume_token(INVARIANT);
      break;
      }
    case PRECISE:{
      token = jj_consume_token(PRECISE);
      break;
      }
    case HIGHP:{
      token = jj_consume_token(HIGHP);
      break;
      }
    case MEDIUMP:{
      token = jj_consume_token(MEDIUMP);
      break;
      }
    case LOWP:{
      token = jj_consume_token(LOWP);
      break;
      }
    case TRUE:{
      token = jj_consume_token(TRUE);
      break;
      }
    case FALSE:{
      token = jj_consume_token(FALSE);
      break;
      }
    case NUMBER:{
      token = jj_consume_token(NUMBER);
      break;
      }
    case IDENTIFIER:{
      token = jj_consume_token(IDENTIFIER);
      break;
      }
    case LEFT_PAREN:{
      token = jj_consume_token(LEFT_PAREN);
      break;
      }
    case RIGHT_PAREN:{
      token = jj_consume_token(RIGHT_PAREN);
      break;
      }
    case LEFT_BRACKET:{
      token = jj_consume_token(LEFT_BRACKET);
      break;
      }
    case RIGHT_BRACKET:{
      token = jj_consume_token(RIGHT_BRACKET);
      break;
      }
    case LEFT_BRACE:{
      token = jj_consume_token(LEFT_BRACE);
      break;
      }
    case RIGHT_BRACE:{
      token = jj_consume_token(RIGHT_BRACE);
      break;
      }
    case COMMA:{
      token = jj_consume_token(COMMA);
      break;
      }
    case SEMICOLON:{
      token = jj_consume_token(SEMICOLON);
      break;
      }
    case EQUAL:{
      token = jj_consume_token(EQUAL);
      break;
      }
    case OTHER:{
      token = jj_consume_token(OTHER);
      break;
      }
    default:
      jj_la1[24] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return token;}
    throw new Error("Missing return statement in function");
}

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_3R_Qualifier_464_5_26()
 {
    if (jj_3R_SimpleQualifier_500_5_29()) return true;
    return false;
  }

  private boolean jj_3R_Qualifier_462_5_25()
 {
    if (jj_3R_StorageQualifier_493_5_28()) return true;
    return false;
  }

  private boolean jj_3R_UniformDeclaration_411_7_20()
 {
    if (jj_3R_Qualifier_460_5_23()) return true;
    return false;
  }

  private boolean jj_3R_Qualifier_460_5_23()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Qualifier_460_5_24()) {
    jj_scanpos = xsp;
    if (jj_3R_Qualifier_462_5_25()) {
    jj_scanpos = xsp;
    if (jj_3R_Qualifier_464_5_26()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_Qualifier_460_5_24()
 {
    if (jj_3R_LayoutQualifier_470_5_27()) return true;
    return false;
  }

  private boolean jj_3R_UniformDeclaration_411_5_16()
 {
    Token xsp;
    if (jj_3R_UniformDeclaration_411_7_20()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_UniformDeclaration_411_7_20()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_SimpleQualifier_500_5_29()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(9)) {
    jj_scanpos = xsp;
    if (jj_scan_token(11)) {
    jj_scanpos = xsp;
    if (jj_scan_token(12)) {
    jj_scanpos = xsp;
    if (jj_scan_token(10)) {
    jj_scanpos = xsp;
    if (jj_scan_token(13)) {
    jj_scanpos = xsp;
    if (jj_scan_token(14)) {
    jj_scanpos = xsp;
    if (jj_scan_token(15)) {
    jj_scanpos = xsp;
    if (jj_scan_token(16)) {
    jj_scanpos = xsp;
    if (jj_scan_token(17)) {
    jj_scanpos = xsp;
    if (jj_scan_token(18)) {
    jj_scanpos = xsp;
    if (jj_scan_token(19)) {
    jj_scanpos = xsp;
    if (jj_scan_token(20)) {
    jj_scanpos = xsp;
    if (jj_scan_token(21)) {
    jj_scanpos = xsp;
    if (jj_scan_token(22)) {
    jj_scanpos = xsp;
    if (jj_scan_token(23)) {
    jj_scanpos = xsp;
    if (jj_scan_token(24)) {
    jj_scanpos = xsp;
    if (jj_scan_token(25)) {
    jj_scanpos = xsp;
    if (jj_scan_token(26)) {
    jj_scanpos = xsp;
    if (jj_scan_token(27)) {
    jj_scanpos = xsp;
    if (jj_scan_token(28)) {
    jj_scanpos = xsp;
    if (jj_scan_token(29)) {
    jj_scanpos = xsp;
    if (jj_scan_token(30)) {
    jj_scanpos = xsp;
    if (jj_scan_token(31)) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_InterfaceBlockDeclaration_399_7_19()
 {
    if (jj_3R_Qualifier_460_5_23()) return true;
    return false;
  }

  private boolean jj_3R_StorageQualifier_493_5_28()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(7)) {
    jj_scanpos = xsp;
    if (jj_scan_token(8)) return true;
    }
    return false;
  }

  private boolean jj_3R_InterfaceBlockDeclaration_399_5_15()
 {
    Token xsp;
    if (jj_3R_InterfaceBlockDeclaration_399_7_19()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_InterfaceBlockDeclaration_399_7_19()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_TranslationUnit_390_9_14()
 {
    if (jj_3R_SkipExternalDeclaration_611_5_18()) return true;
    return false;
  }

  private boolean jj_3R_TranslationUnit_387_9_13()
 {
    if (jj_3R_StructDeclaration_420_5_17()) return true;
    return false;
  }

  private boolean jj_3R_TranslationUnit_384_9_12()
 {
    if (jj_3R_UniformDeclaration_411_5_16()) return true;
    return false;
  }

  private boolean jj_3R_TranslationUnit_381_9_11()
 {
    if (jj_3R_InterfaceBlockDeclaration_399_5_15()) return true;
    return false;
  }

  private boolean jj_3_1()
 {
    Token xsp;
    xsp = jj_scanpos;
    jj_lookingAhead = true;
    jj_semLA = isInterfaceBlockAhead();
    jj_lookingAhead = false;
    if (!jj_semLA || jj_3R_TranslationUnit_381_9_11()) {
    jj_scanpos = xsp;
    jj_lookingAhead = true;
    jj_semLA = isUniformDeclarationAhead();
    jj_lookingAhead = false;
    if (!jj_semLA || jj_3R_TranslationUnit_384_9_12()) {
    jj_scanpos = xsp;
    jj_lookingAhead = true;
    jj_semLA = isStructDeclarationAhead();
    jj_lookingAhead = false;
    if (!jj_semLA || jj_3R_TranslationUnit_387_9_13()) {
    jj_scanpos = xsp;
    if (jj_3R_TranslationUnit_390_9_14()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_AnyToken_618_5_22()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(5)) {
    jj_scanpos = xsp;
    if (jj_scan_token(6)) {
    jj_scanpos = xsp;
    if (jj_scan_token(7)) {
    jj_scanpos = xsp;
    if (jj_scan_token(8)) {
    jj_scanpos = xsp;
    if (jj_scan_token(9)) {
    jj_scanpos = xsp;
    if (jj_scan_token(10)) {
    jj_scanpos = xsp;
    if (jj_scan_token(11)) {
    jj_scanpos = xsp;
    if (jj_scan_token(12)) {
    jj_scanpos = xsp;
    if (jj_scan_token(13)) {
    jj_scanpos = xsp;
    if (jj_scan_token(14)) {
    jj_scanpos = xsp;
    if (jj_scan_token(15)) {
    jj_scanpos = xsp;
    if (jj_scan_token(16)) {
    jj_scanpos = xsp;
    if (jj_scan_token(17)) {
    jj_scanpos = xsp;
    if (jj_scan_token(18)) {
    jj_scanpos = xsp;
    if (jj_scan_token(19)) {
    jj_scanpos = xsp;
    if (jj_scan_token(20)) {
    jj_scanpos = xsp;
    if (jj_scan_token(21)) {
    jj_scanpos = xsp;
    if (jj_scan_token(22)) {
    jj_scanpos = xsp;
    if (jj_scan_token(23)) {
    jj_scanpos = xsp;
    if (jj_scan_token(24)) {
    jj_scanpos = xsp;
    if (jj_scan_token(25)) {
    jj_scanpos = xsp;
    if (jj_scan_token(26)) {
    jj_scanpos = xsp;
    if (jj_scan_token(27)) {
    jj_scanpos = xsp;
    if (jj_scan_token(28)) {
    jj_scanpos = xsp;
    if (jj_scan_token(29)) {
    jj_scanpos = xsp;
    if (jj_scan_token(30)) {
    jj_scanpos = xsp;
    if (jj_scan_token(31)) {
    jj_scanpos = xsp;
    if (jj_scan_token(32)) {
    jj_scanpos = xsp;
    if (jj_scan_token(33)) {
    jj_scanpos = xsp;
    if (jj_scan_token(34)) {
    jj_scanpos = xsp;
    if (jj_scan_token(35)) {
    jj_scanpos = xsp;
    if (jj_scan_token(36)) {
    jj_scanpos = xsp;
    if (jj_scan_token(37)) {
    jj_scanpos = xsp;
    if (jj_scan_token(38)) {
    jj_scanpos = xsp;
    if (jj_scan_token(39)) {
    jj_scanpos = xsp;
    if (jj_scan_token(40)) {
    jj_scanpos = xsp;
    if (jj_scan_token(41)) {
    jj_scanpos = xsp;
    if (jj_scan_token(42)) {
    jj_scanpos = xsp;
    if (jj_scan_token(43)) {
    jj_scanpos = xsp;
    if (jj_scan_token(44)) {
    jj_scanpos = xsp;
    if (jj_scan_token(45)) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_StructSpecifier_428_5_21()
 {
    if (jj_scan_token(STRUCT)) return true;
    return false;
  }

  private boolean jj_3R_LayoutQualifier_470_5_27()
 {
    if (jj_scan_token(LAYOUT)) return true;
    return false;
  }

  private boolean jj_3R_SkipExternalDeclaration_611_5_18()
 {
    if (jj_3R_AnyToken_618_5_22()) return true;
    return false;
  }

  private boolean jj_3R_StructDeclaration_420_5_17()
 {
    if (jj_3R_StructSpecifier_428_5_21()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public GLSLResourceParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  /** Whether we are looking ahead. */
  private boolean jj_lookingAhead = false;
  private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[25];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0xffffffe0,0xffffffa0,0xffffffe0,0x0,0xffffffa0,0x0,0x0,0xffffffe0,0xffffffa0,0x40,0x0,0xffffffa0,0x0,0x10000,0x0,0x180,0xfffffe00,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xffffffe0,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x3fff,0x0,0x8,0x8,0x0,0x8,0x8,0x8,0x0,0x8,0x40,0x0,0x400,0x8,0x1000,0x0,0x0,0x400,0x40,0x1000,0x400,0x40,0x40,0x40,0x3fff,};
	}
  final private JJCalls[] jj_2_rtns = new JJCalls[1];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public GLSLResourceParser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public GLSLResourceParser(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new GLSLResourceParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 25; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 25; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public GLSLResourceParser(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new GLSLResourceParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 25; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new GLSLResourceParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 25; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public GLSLResourceParser(GLSLResourceParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 25; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(GLSLResourceParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 25; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = jj_lookingAhead ? jj_scanpos : token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[46];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 25; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 46; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 1; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
