/* GLSLResourceParserTokenManager.java */
/* Generated By:JJTree&JavaCC: Do not edit this line. GLSLResourceParserTokenManager.java */
package com.cleanroommc.kirino.gl.shader.parser;

/** Token Manager. */
public class GLSLResourceParserTokenManager implements GLSLResourceParserConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0){
   switch (pos)
   {
      case 0:
         if ((active0 & 0x3ffffffe0L) != 0L)
         {
            jjmatchedKind = 35;
            return 26;
         }
         return -1;
      case 1:
         if ((active0 & 0x8000c00L) != 0L)
            return 26;
         if ((active0 & 0x3f7fff3e0L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 35;
               jjmatchedPos = 1;
            }
            return 26;
         }
         return -1;
      case 2:
         if ((active0 & 0x3ffffe7e0L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 2;
            return 26;
         }
         if ((active0 & 0x1000L) != 0L)
            return 26;
         return -1;
      case 3:
         if ((active0 & 0x182000000L) != 0L)
            return 26;
         if ((active0 & 0x27dffe7e0L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 3;
            return 26;
         }
         return -1;
      case 4:
         if ((active0 & 0x220004600L) != 0L)
            return 26;
         if ((active0 & 0x5dffa1e0L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 4;
            return 26;
         }
         return -1;
      case 5:
         if ((active0 & 0x1018160L) != 0L)
            return 26;
         if ((active0 & 0x5cfe2080L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 5;
            return 26;
         }
         return -1;
      case 6:
         if ((active0 & 0xc7e2000L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 6;
            return 26;
         }
         if ((active0 & 0x50800080L) != 0L)
            return 26;
         return -1;
      case 7:
         if ((active0 & 0x1e2000L) != 0L)
            return 26;
         if ((active0 & 0xc600000L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 7;
            return 26;
         }
         return -1;
      case 8:
         if ((active0 & 0x8600000L) != 0L)
            return 26;
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 8;
            return 26;
         }
         return -1;
      case 9:
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 9;
            return 26;
         }
         return -1;
      case 10:
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 10;
            return 26;
         }
         return -1;
      case 11:
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 11;
            return 26;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 40:
         return jjStopAtPos(0, 36);
      case 41:
         return jjStopAtPos(0, 37);
      case 44:
         return jjStopAtPos(0, 42);
      case 59:
         return jjStopAtPos(0, 43);
      case 61:
         return jjStopAtPos(0, 44);
      case 91:
         return jjStopAtPos(0, 38);
      case 93:
         return jjStopAtPos(0, 39);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x400000L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x100L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x22200L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x202000000L);
      case 104:
         return jjMoveStringLiteralDfa1_0(0x20000000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x8000c00L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x80000020L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x40000000L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x4000000L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x1000L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x10004000L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x180000L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x1018040L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x100000000L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x80L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x840000L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x200000L);
      case 123:
         return jjStopAtPos(0, 40);
      case 125:
         return jjStopAtPos(0, 41);
      default :
         return jjMoveNfa_0(1, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x20080c020L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x40182000L);
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000L);
      case 110:
         if ((active0 & 0x800L) != 0L)
         {
            jjmatchedKind = 11;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x8000480L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x84060200L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x110200000L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x400040L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x1100L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x2110000L);
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x100L);
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000L);
      case 104:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x200080L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x200040000L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x2200L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000400L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x800040L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000L);
      case 116:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(2, 12, 26);
         return jjMoveStringLiteralDfa3_0(active0, 0x404000L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000L);
      case 118:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000L);
      case 119:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000L);
      case 121:
         return jjMoveStringLiteralDfa3_0(active0, 0x20L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x8040000L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x10004000L);
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000L);
      case 101:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(3, 32, 26);
         return jjMoveStringLiteralDfa4_0(active0, 0x4020000L);
      case 102:
         return jjMoveStringLiteralDfa4_0(active0, 0x180L);
      case 104:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000000L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000020L);
      case 112:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(3, 31, 26);
         return jjMoveStringLiteralDfa4_0(active0, 0x8000L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x410000L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000200L);
      case 116:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(3, 25, 26);
         return jjMoveStringLiteralDfa4_0(active0, 0x282000L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x440L);
      case 121:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x40L);
      case 101:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(4, 33, 26);
         return jjMoveStringLiteralDfa5_0(active0, 0x210100L);
      case 104:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(4, 14, 26);
         break;
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x10c00000L);
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x100080L);
      case 112:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(4, 29, 26);
         break;
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0xc0a2000L);
      case 116:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(4, 9, 26);
         else if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(4, 10, 26);
         return jjMoveStringLiteralDfa5_0(active0, 0x1040000L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000020L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 98:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000L);
      case 100:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(5, 16, 26);
         break;
      case 101:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(5, 15, 26);
         return jjMoveStringLiteralDfa6_0(active0, 0x20000L);
      case 104:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(5, 24, 26);
         break;
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x80c0000L);
      case 109:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000L);
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0x900000L);
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x202000L);
      case 114:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(5, 8, 26);
         return jjMoveStringLiteralDfa6_0(active0, 0x80L);
      case 115:
         return jjMoveStringLiteralDfa6_0(active0, 0x14000000L);
      case 116:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(5, 5, 26);
         else if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(5, 6, 26);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000L);
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x80000L);
      case 101:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(6, 28, 26);
         break;
      case 103:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(6, 23, 26);
         break;
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000L);
      case 108:
         return jjMoveStringLiteralDfa7_0(active0, 0x140000L);
      case 109:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(6, 7, 26);
         break;
      case 110:
         return jjMoveStringLiteralDfa7_0(active0, 0x220000L);
      case 112:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(6, 30, 26);
         return jjMoveStringLiteralDfa7_0(active0, 0x4000000L);
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x400000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 100:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(7, 13, 26);
         break;
      case 101:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(7, 18, 26);
         return jjMoveStringLiteralDfa8_0(active0, 0x4000000L);
      case 108:
         return jjMoveStringLiteralDfa8_0(active0, 0x200000L);
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000000L);
      case 116:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(7, 17, 26);
         else if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(7, 19, 26);
         return jjMoveStringLiteralDfa8_0(active0, 0x400000L);
      case 121:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(7, 20, 26);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa9_0(active0, 0x4000000L);
      case 101:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(8, 22, 26);
         break;
      case 116:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(8, 27, 26);
         break;
      case 121:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(8, 21, 26);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 116:
         return jjMoveStringLiteralDfa10_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 105:
         return jjMoveStringLiteralDfa11_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 118:
         return jjMoveStringLiteralDfa12_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(12, 26, 26);
         break;
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 39;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 34)
                        kind = 34;
                     { jjCheckNAddStates(0, 4); }
                  }
                  else if ((0x100002600L & l) != 0L)
                  {
                     if (kind > 1)
                        kind = 1;
                     { jjCheckNAdd(0); }
                  }
                  else if (curChar == 47)
                     { jjAddStates(5, 6); }
                  else if (curChar == 46)
                     { jjCheckNAdd(24); }
                  else if (curChar == 35)
                  {
                     if (kind > 4)
                        kind = 4;
                     { jjCheckNAddStates(7, 10); }
                  }
                  if (curChar == 48)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 0:
                  if ((0x100002600L & l) == 0L)
                     break;
                  if (kind > 1)
                     kind = 1;
                  { jjCheckNAdd(0); }
                  break;
               case 3:
                  if (curChar != 10)
                     break;
                  if (kind > 4)
                     kind = 4;
                  { jjCheckNAddStates(7, 10); }
                  break;
               case 4:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 4)
                     kind = 4;
                  { jjCheckNAddStates(7, 10); }
                  break;
               case 5:
                  if (curChar == 10 && kind > 4)
                     kind = 4;
                  break;
               case 6:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 7:
                  if ((0x2400L & l) != 0L && kind > 4)
                     kind = 4;
                  break;
               case 8:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 9:
                  if ((0x2400L & l) == 0L)
                     break;
                  if (kind > 4)
                     kind = 4;
                  { jjCheckNAddStates(7, 10); }
                  break;
               case 10:
                  if (curChar == 48)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 12:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 34)
                     kind = 34;
                  { jjAddStates(11, 12); }
                  break;
               case 14:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 34)
                     kind = 34;
                  { jjCheckNAddStates(0, 4); }
                  break;
               case 15:
                  if (curChar != 46)
                     break;
                  if (kind > 34)
                     kind = 34;
                  { jjCheckNAddStates(13, 16); }
                  break;
               case 16:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 34)
                     kind = 34;
                  { jjCheckNAddStates(13, 16); }
                  break;
               case 18:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(19); }
                  break;
               case 19:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 34)
                     kind = 34;
                  { jjCheckNAddStates(17, 19); }
                  break;
               case 23:
                  if (curChar == 46)
                     { jjCheckNAdd(24); }
                  break;
               case 24:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 34)
                     kind = 34;
                  { jjCheckNAddStates(20, 23); }
                  break;
               case 26:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 35)
                     kind = 35;
                  jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 27:
                  if (curChar == 47)
                     { jjAddStates(5, 6); }
                  break;
               case 28:
                  if (curChar != 47)
                     break;
                  if (kind > 2)
                     kind = 2;
                  { jjCheckNAddStates(24, 26); }
                  break;
               case 29:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 2)
                     kind = 2;
                  { jjCheckNAddStates(24, 26); }
                  break;
               case 30:
                  if (curChar == 10 && kind > 2)
                     kind = 2;
                  break;
               case 31:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 32:
                  if ((0x2400L & l) != 0L && kind > 2)
                     kind = 2;
                  break;
               case 33:
                  if (curChar == 42)
                     { jjCheckNAddStates(27, 29); }
                  break;
               case 34:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     { jjCheckNAddStates(27, 29); }
                  break;
               case 35:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 36:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     { jjCheckNAddStates(27, 29); }
                  break;
               case 37:
                  if (curChar == 47 && kind > 3)
                     kind = 3;
                  break;
               case 38:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
               case 26:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 35)
                     kind = 35;
                  { jjCheckNAdd(26); }
                  break;
               case 2:
                  if (curChar == 92)
                     { jjAddStates(30, 31); }
                  break;
               case 4:
                  if (kind > 4)
                     kind = 4;
                  { jjAddStates(7, 10); }
                  break;
               case 11:
                  if ((0x100000001000000L & l) != 0L)
                     { jjCheckNAdd(12); }
                  break;
               case 12:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 34)
                     kind = 34;
                  { jjCheckNAddTwoStates(12, 13); }
                  break;
               case 13:
                  if ((0x20000000200000L & l) != 0L && kind > 34)
                     kind = 34;
                  break;
               case 17:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(32, 33); }
                  break;
               case 20:
                  if ((0x20004000200040L & l) != 0L && kind > 34)
                     kind = 34;
                  break;
               case 21:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 22:
                  if ((0x4000000040L & l) != 0L && kind > 34)
                     kind = 34;
                  break;
               case 29:
                  if (kind > 2)
                     kind = 2;
                  { jjAddStates(24, 26); }
                  break;
               case 34:
               case 36:
                  { jjCheckNAddStates(27, 29); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 4:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 4)
                     kind = 4;
                  { jjAddStates(7, 10); }
                  break;
               case 29:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 2)
                     kind = 2;
                  { jjAddStates(24, 26); }
                  break;
               case 34:
               case 36:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddStates(27, 29); }
                  break;
               default : if (i1 == 0 || l1 == 0 || i2 == 0 ||  l2 == 0) break; else break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 39 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, "\154\141\171\157\165\164", 
"\163\164\162\165\143\164", "\165\156\151\146\157\162\155", "\142\165\146\146\145\162", 
"\143\157\156\163\164", "\151\156\157\165\164", "\151\156", "\157\165\164", 
"\143\145\156\164\162\157\151\144", "\160\141\164\143\150", "\163\141\155\160\154\145", 
"\163\150\141\162\145\144", "\143\157\150\145\162\145\156\164", "\166\157\154\141\164\151\154\145", 
"\162\145\163\164\162\151\143\164", "\162\145\141\144\157\156\154\171", "\167\162\151\164\145\157\156\154\171", 
"\141\164\164\162\151\142\165\164\145", "\166\141\162\171\151\156\147", "\163\155\157\157\164\150", 
"\146\154\141\164", "\156\157\160\145\162\163\160\145\143\164\151\166\145", 
"\151\156\166\141\162\151\141\156\164", "\160\162\145\143\151\163\145", "\150\151\147\150\160", 
"\155\145\144\151\165\155\160", "\154\157\167\160", "\164\162\165\145", "\146\141\154\163\145", null, null, 
"\50", "\51", "\133", "\135", "\173", "\175", "\54", "\73", "\75", null, };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   14, 15, 17, 20, 21, 28, 33, 2, 4, 6, 7, 12, 13, 16, 17, 20, 
   21, 19, 20, 21, 24, 17, 20, 21, 29, 31, 32, 34, 35, 38, 8, 9, 
   18, 19, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default :
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedPos == 0 && jjmatchedKind > 45)
   {
      jjmatchedKind = 45;
   }
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public GLSLResourceParserTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public GLSLResourceParserTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 39; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0x3fffffffffe1L, 
};
static final long[] jjtoSkip = {
   0x1eL, 
};
static final long[] jjtoSpecial = {
   0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[39];
    private final int[] jjstateSet = new int[2 * 39];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected int curChar;
}
