/* Generated By:JJTree&JavaCC: Do not edit this line. GLSLResourceParserConstants.java */
package com.cleanroommc.kirino.gl.shader.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GLSLResourceParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITE_SPACE = 1;
  /** RegularExpression Id. */
  int LINE_COMMENT = 2;
  /** RegularExpression Id. */
  int BLOCK_COMMENT = 3;
  /** RegularExpression Id. */
  int PREPROCESSOR_DIRECTIVE = 4;
  /** RegularExpression Id. */
  int LAYOUT = 5;
  /** RegularExpression Id. */
  int STRUCT = 6;
  /** RegularExpression Id. */
  int UNIFORM = 7;
  /** RegularExpression Id. */
  int BUFFER = 8;
  /** RegularExpression Id. */
  int CONST = 9;
  /** RegularExpression Id. */
  int INOUT = 10;
  /** RegularExpression Id. */
  int IN = 11;
  /** RegularExpression Id. */
  int OUT = 12;
  /** RegularExpression Id. */
  int CENTROID = 13;
  /** RegularExpression Id. */
  int PATCH = 14;
  /** RegularExpression Id. */
  int SAMPLE = 15;
  /** RegularExpression Id. */
  int SHARED = 16;
  /** RegularExpression Id. */
  int COHERENT = 17;
  /** RegularExpression Id. */
  int VOLATILE = 18;
  /** RegularExpression Id. */
  int RESTRICT = 19;
  /** RegularExpression Id. */
  int READONLY = 20;
  /** RegularExpression Id. */
  int WRITEONLY = 21;
  /** RegularExpression Id. */
  int ATTRIBUTE = 22;
  /** RegularExpression Id. */
  int VARYING = 23;
  /** RegularExpression Id. */
  int SMOOTH = 24;
  /** RegularExpression Id. */
  int FLAT = 25;
  /** RegularExpression Id. */
  int NOPERSPECTIVE = 26;
  /** RegularExpression Id. */
  int INVARIANT = 27;
  /** RegularExpression Id. */
  int PRECISE = 28;
  /** RegularExpression Id. */
  int HIGHP = 29;
  /** RegularExpression Id. */
  int MEDIUMP = 30;
  /** RegularExpression Id. */
  int LOWP = 31;
  /** RegularExpression Id. */
  int TRUE = 32;
  /** RegularExpression Id. */
  int FALSE = 33;
  /** RegularExpression Id. */
  int NUMBER = 34;
  /** RegularExpression Id. */
  int IDENTIFIER = 35;
  /** RegularExpression Id. */
  int LEFT_PAREN = 36;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 37;
  /** RegularExpression Id. */
  int LEFT_BRACKET = 38;
  /** RegularExpression Id. */
  int RIGHT_BRACKET = 39;
  /** RegularExpression Id. */
  int LEFT_BRACE = 40;
  /** RegularExpression Id. */
  int RIGHT_BRACE = 41;
  /** RegularExpression Id. */
  int COMMA = 42;
  /** RegularExpression Id. */
  int SEMICOLON = 43;
  /** RegularExpression Id. */
  int EQUAL = 44;
  /** RegularExpression Id. */
  int OTHER = 45;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITE_SPACE>",
    "<LINE_COMMENT>",
    "<BLOCK_COMMENT>",
    "<PREPROCESSOR_DIRECTIVE>",
    "\"layout\"",
    "\"struct\"",
    "\"uniform\"",
    "\"buffer\"",
    "\"const\"",
    "\"inout\"",
    "\"in\"",
    "\"out\"",
    "\"centroid\"",
    "\"patch\"",
    "\"sample\"",
    "\"shared\"",
    "\"coherent\"",
    "\"volatile\"",
    "\"restrict\"",
    "\"readonly\"",
    "\"writeonly\"",
    "\"attribute\"",
    "\"varying\"",
    "\"smooth\"",
    "\"flat\"",
    "\"noperspective\"",
    "\"invariant\"",
    "\"precise\"",
    "\"highp\"",
    "\"mediump\"",
    "\"lowp\"",
    "\"true\"",
    "\"false\"",
    "<NUMBER>",
    "<IDENTIFIER>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\";\"",
    "\"=\"",
    "<OTHER>",
  };

}
