/* Generated By:JavaCC: Do not edit this line. GLSLResourceParserTreeConstants.java Version 7.0.13 */
package com.cleanroommc.kirino.gl.shader.parser;

public interface GLSLResourceParserTreeConstants
{
  public int JJTTRANSLATIONUNIT = 0;
  public int JJTGLOBALLAYOUTDECLARATION = 1;
  public int JJTSTORAGEQUALIFIER = 2;
  public int JJTINTERFACEBLOCKDECLARATION = 3;
  public int JJTUNIFORMDECLARATION = 4;
  public int JJTINPUTOUTPUTDECLARATION = 5;
  public int JJTSTRUCTDECLARATION = 6;
  public int JJTSTRUCTSPECIFIER = 7;
  public int JJTMEMBERDECLARATION = 8;
  public int JJTTYPESPECIFIER = 9;
  public int JJTVOID = 10;
  public int JJTLAYOUTQUALIFIER = 11;
  public int JJTLAYOUTQUALIFIERITEM = 12;
  public int JJTQUALIFIER = 13;
  public int JJTDECLARATORLIST = 14;
  public int JJTDECLARATOR = 15;
  public int JJTINSTANCEDECLARATOR = 16;
  public int JJTARRAYSPECIFIER = 17;
  public int JJTARRAYDIMENSION = 18;
  public int JJTINITIALIZER = 19;
  public int JJTBLOCKNAME = 20;
  public int JJTSTRUCTNAME = 21;


  public String[] jjtNodeName = {
    "TranslationUnit",
    "GlobalLayoutDeclaration",
    "StorageQualifier",
    "InterfaceBlockDeclaration",
    "UniformDeclaration",
    "InputOutputDeclaration",
    "StructDeclaration",
    "StructSpecifier",
    "MemberDeclaration",
    "TypeSpecifier",
    "void",
    "LayoutQualifier",
    "LayoutQualifierItem",
    "Qualifier",
    "DeclaratorList",
    "Declarator",
    "InstanceDeclarator",
    "ArraySpecifier",
    "ArrayDimension",
    "Initializer",
    "BlockName",
    "StructName",
  };
}
/* JavaCC - OriginalChecksum=95958c009a4cbc17219f402c80dd841c (do not edit this line) */
