/* Generated By:JavaCC: Do not edit this line. GLSLResourceParserTreeConstants.java Version 7.0.13 */
package com.cleanroommc.kirino.gl.shader.parser;

public interface GLSLResourceParserTreeConstants
{
  public int JJTTRANSLATIONUNIT = 0;
  public int JJTINTERFACEBLOCKDECLARATION = 1;
  public int JJTUNIFORMDECLARATION = 2;
  public int JJTSTRUCTDECLARATION = 3;
  public int JJTSTRUCTSPECIFIER = 4;
  public int JJTMEMBERDECLARATION = 5;
  public int JJTTYPESPECIFIER = 6;
  public int JJTVOID = 7;
  public int JJTLAYOUTQUALIFIER = 8;
  public int JJTLAYOUTQUALIFIERITEM = 9;
  public int JJTSTORAGEQUALIFIER = 10;
  public int JJTQUALIFIER = 11;
  public int JJTDECLARATORLIST = 12;
  public int JJTDECLARATOR = 13;
  public int JJTINSTANCEDECLARATOR = 14;
  public int JJTARRAYSPECIFIER = 15;
  public int JJTARRAYDIMENSION = 16;
  public int JJTINITIALIZER = 17;
  public int JJTBLOCKNAME = 18;
  public int JJTSTRUCTNAME = 19;


  public String[] jjtNodeName = {
    "TranslationUnit",
    "InterfaceBlockDeclaration",
    "UniformDeclaration",
    "StructDeclaration",
    "StructSpecifier",
    "MemberDeclaration",
    "TypeSpecifier",
    "void",
    "LayoutQualifier",
    "LayoutQualifierItem",
    "StorageQualifier",
    "Qualifier",
    "DeclaratorList",
    "Declarator",
    "InstanceDeclarator",
    "ArraySpecifier",
    "ArrayDimension",
    "Initializer",
    "BlockName",
    "StructName",
  };
}
/* JavaCC - OriginalChecksum=04b4a6dbfb532b14745f224167f9ef07 (do not edit this line) */
