/* Generated By:JavaCC: Do not edit this line. GLSLResourceParserDefaultVisitor.java Version 7.0.13 */
package com.cleanroommc.kirino.gl.shader.parser;

public class GLSLResourceParserDefaultVisitor implements GLSLResourceParserVisitor{
  public Void defaultVisit(SimpleNode node, Void data){
    node.childrenAccept(this, data);
    return data;
  }
  public Void visit(SimpleNode node, Void data){
    return defaultVisit(node, data);
  }
  public Void visit(ASTTranslationUnit node, Void data){
    return defaultVisit(node, data);
  }
  public Void visit(ASTInterfaceBlockDeclaration node, Void data){
    return defaultVisit(node, data);
  }
  public Void visit(ASTUniformDeclaration node, Void data){
    return defaultVisit(node, data);
  }
  public Void visit(ASTStructDeclaration node, Void data){
    return defaultVisit(node, data);
  }
  public Void visit(ASTStructSpecifier node, Void data){
    return defaultVisit(node, data);
  }
  public Void visit(ASTMemberDeclaration node, Void data){
    return defaultVisit(node, data);
  }
  public Void visit(ASTTypeSpecifier node, Void data){
    return defaultVisit(node, data);
  }
  public Void visit(ASTLayoutQualifier node, Void data){
    return defaultVisit(node, data);
  }
  public Void visit(ASTLayoutQualifierItem node, Void data){
    return defaultVisit(node, data);
  }
  public Void visit(ASTStorageQualifier node, Void data){
    return defaultVisit(node, data);
  }
  public Void visit(ASTQualifier node, Void data){
    return defaultVisit(node, data);
  }
  public Void visit(ASTDeclaratorList node, Void data){
    return defaultVisit(node, data);
  }
  public Void visit(ASTDeclarator node, Void data){
    return defaultVisit(node, data);
  }
  public Void visit(ASTInstanceDeclarator node, Void data){
    return defaultVisit(node, data);
  }
  public Void visit(ASTArraySpecifier node, Void data){
    return defaultVisit(node, data);
  }
  public Void visit(ASTArrayDimension node, Void data){
    return defaultVisit(node, data);
  }
  public Void visit(ASTInitializer node, Void data){
    return defaultVisit(node, data);
  }
  public Void visit(ASTBlockName node, Void data){
    return defaultVisit(node, data);
  }
  public Void visit(ASTStructName node, Void data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=78759e2025f3850a63f0429cb9fafac2 (do not edit this line) */
